[phases.setup]
nixPkgs = ["python39", "gcc"]
aptPkgs = ["libpq-dev"]

[phases.install]
cmds = ["python3 -m venv /opt/venv", ". /opt/venv/bin/activate && pip install -r requirements.txt"]

[phases.build]
cmds = ["mkdir -p static/uploads instance"]

[start]
cmd = ". /opt/venv/bin/activate && gunicorn app:app --bind 0.0.0.0:$PORT"
